-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2024-10-29 23:04:59.607

-- foreign keys
ALTER TABLE PORTFOLIOS
    DROP CONSTRAINT PORTFOLIOS_USERS;

ALTER TABLE STOCKS_PORTFOLIOS
    DROP CONSTRAINT STOCKS_PORTFOLIOS_PORTFOLIOS;

ALTER TABLE STOCKS_PORTFOLIOS
    DROP CONSTRAINT STOCKS_PORTFOLIOS_STOCKS;

ALTER TABLE TRANSACTIONS
    DROP CONSTRAINT TRANSACTIONS_PORTFOLIOS;

ALTER TABLE TRANSACTIONS
    DROP CONSTRAINT TRANSACTIONS_STOCKS;

ALTER TABLE TRANSACTIONS
    DROP CONSTRAINT TRANSACTIONS_TRANSACTION_TYPES;

-- tables
DROP TABLE PORTFOLIOS;

DROP TABLE STOCKS;

DROP TABLE STOCKS_PORTFOLIOS;

DROP TABLE TRANSACTIONS;

DROP TABLE TRANSACTION_TYPES;

DROP TABLE USERS;

-- End of file.

